name: TogglePvP
version: 1.5
main: me.becja10.TogglePvP.Main
commands:
  togglepvp:
    description: Toggle pvp enabled/disabled
    usage: /togglepvp <player>
    aliases: [tpvp]
    
  togglepvpreset: 
    description: Admin tool to reset a player's cooldown timer
    usage: /togglepvpreset <player>
    aliases: [tpvpr]
