name: TogglePvP
version: 4.0
main: me.becja10.TogglePvP.TogglePvP
description: Allows players to toggle between PvP and PvE
commands:
  togglepvp:
    description: Toggle pvp enabled/disabled
    usage: /togglepvp [player]
    aliases: [tpvp] 
  togglepvpreset: 
    description: Admin tool to reset a player's cooldown timer
    usage: /togglepvpreset <player>
    aliases: [tpvpr]
  togglepvpcheck:
    description: Allows players to check if another player or themself is PvP/PvE
    usage: /togglepvpcheck [player]
    aliases: [check, tpvpc]
  togglepvptime:
    description: Check how much time you have before you can toggle. Also returns a list of everyone with a timer if the argument "list" is provided
    usage: /togglepvptime [player|list]
    aliases: [tpvpt, tpvptime]
  togglepvpreload:
    description: Reloads the player data and configs
    usage: /togglepvpreload 
    aliases: [tpvpreload]
  lockpvp:
    description: Locks a player's pvp status
    usage: /lockpvp <player> <true|false>
  unlockpvp:
    description: Unlocks a player's pvp status
    usage: /unlockpvp <player>
